import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { loadCore, type CoreSet, type Doc, type Skill } from '../lib/core.ts';
import { AtrixError, log } from '../lib/log.ts';
import { harnessPaths } from '../lib/paths.ts';

/**
 * Generate per-agent packaging from the portable core.
 *
 * adapters/ is disposable output — never hand-edited. Everything here is derived
 * from core/, which is why adding a new agent is an adapter and not a rewrite.
 */

const GENERATED_BANNER =
  '<!-- GENERATED by `atrix build` from core/. Do not edit — edit core/ and rebuild. -->';

function write(file: string, contents: string): void {
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, contents.endsWith('\n') ? contents : `${contents}\n`, 'utf8');
}

/** Rules + methodology, concatenated into one document an agent reads on start. */
function renderRuleBundle(core: CoreSet, agentsMd: string): string {
  const sections = [...core.rules, ...core.methodology]
    .sort((a, b) => a.meta.name.localeCompare(b.meta.name))
    .map((doc) => `## ${doc.meta.name}\n\n${doc.body}`);

  return [GENERATED_BANNER, '', agentsMd.trim(), '', '---', '', '# Rules & methodology', '', ...sections].join(
    '\n',
  );
}

function copySkill(harnessRoot: string, skill: Doc<Skill>, destDir: string): void {
  const srcDir = join(harnessRoot, dirname(skill.path));
  mkdirSync(destDir, { recursive: true });
  cpSync(srcDir, destDir, { recursive: true });
}

function buildClaude(harnessRoot: string, core: CoreSet, agentsMd: string): number {
  const out = join(harnessPaths(harnessRoot).adapters, 'claude');
  rmSync(out, { recursive: true, force: true });

  const plugins = [
    {
      name: 'atrix-core',
      description:
        'Atrix harness core — engineering roles, rules, methodology and the learning loop. Install this first.',
    },
    {
      name: 'atrix-skills',
      description: 'The Atrix skill library — engineering, methodology, delivery, infra, documents and communication.',
    },
    { name: 'atrix-stack', description: 'Atrix stack conventions — Next.js, Elysia/Bun, Prisma, Kysely, Expo, Stripe.' },
  ];

  write(
    join(out, '.claude-plugin', 'marketplace.json'),
    JSON.stringify(
      {
        name: 'atrix-harness',
        description: 'The Atrix agent operating system.',
        owner: { name: 'Atrix', email: 'hello@atrix.dev' },
        plugins: plugins.map((p) => ({
          name: p.name,
          description: p.description,
          author: { name: 'Atrix' },
          category: 'productivity',
          source: `./plugins/${p.name}`,
        })),
      },
      null,
      2,
    ),
  );

  for (const p of plugins) {
    write(
      join(out, 'plugins', p.name, '.claude-plugin', 'plugin.json'),
      JSON.stringify({ name: p.name, description: p.description, version: '0.1.0', author: { name: 'Atrix' } }, null, 2),
    );
  }

  const coreDir = join(out, 'plugins', 'atrix-core');
  write(join(coreDir, 'AGENTS.md'), renderRuleBundle(core, agentsMd));

  for (const role of core.roles) {
    const fm: string[] = [`name: ${role.meta.name}`, `description: ${role.meta.description}`];
    if (role.meta.model !== 'inherit') fm.push(`model: ${role.meta.model}`);
    if (role.meta.tools.length > 0) fm.push(`tools:\n${role.meta.tools.map((t) => `  - ${t}`).join('\n')}`);
    write(join(coreDir, 'agents', `${role.meta.name}.md`), `---\n${fm.join('\n')}\n---\n\n${role.body}`);
  }

  let skillCount = 0;
  for (const skill of core.skills) {
    const plugin = skill.meta.group === 'stack' ? 'atrix-stack' : 'atrix-skills';
    copySkill(harnessRoot, skill, join(out, 'plugins', plugin, 'skills', skill.meta.name));
    skillCount += 1;
  }

  return skillCount;
}

/** Codex and Gemini read a single markdown file; the bundle is the whole payload. */
function buildFlatFile(harnessRoot: string, core: CoreSet, agentsMd: string, agent: string, filename: string): void {
  const out = join(harnessPaths(harnessRoot).adapters, agent);
  rmSync(out, { recursive: true, force: true });
  write(join(out, filename), renderRuleBundle(core, agentsMd));

  // Skills are still useful to these agents as reference material they can be pointed at.
  for (const skill of core.skills) copySkill(harnessRoot, skill, join(out, 'skills', skill.meta.name));
}

/** Cursor uses .mdc rule files with per-rule glob scoping. */
function buildCursor(harnessRoot: string, core: CoreSet, agentsMd: string): void {
  const out = join(harnessPaths(harnessRoot).adapters, 'cursor');
  rmSync(out, { recursive: true, force: true });

  write(join(out, '.cursor', 'rules', '000-atrix-entry.mdc'), `---\nalwaysApply: true\n---\n\n${agentsMd.trim()}`);

  for (const doc of [...core.rules, ...core.methodology]) {
    write(
      join(out, '.cursor', 'rules', `${doc.meta.name}.mdc`),
      `---\ndescription: ${doc.meta.description}\nglobs: ${doc.meta.applies.join(',')}\n---\n\n${doc.body}`,
    );
  }
}

/** Orca launches other agents; it needs to know which adapter each one consumes. */
function buildOrca(harnessRoot: string): void {
  const out = join(harnessPaths(harnessRoot).adapters, 'orca');
  rmSync(out, { recursive: true, force: true });
  write(
    join(out, 'atrix-agents.json'),
    JSON.stringify(
      {
        $comment: 'Generated by `atrix build`. Maps each Orca-launchable agent to its generated adapter.',
        agents: {
          claude: { entry: 'adapters/claude/plugins/atrix-core/AGENTS.md', marketplace: 'adapters/claude' },
          codex: { entry: 'adapters/codex/AGENTS.md' },
          gemini: { entry: 'adapters/gemini/GEMINI.md' },
          cursor: { entry: 'adapters/cursor/.cursor/rules' },
        },
      },
      null,
      2,
    ),
  );
}

export function build(harnessRoot: string): void {
  const p = harnessPaths(harnessRoot);
  const core = loadCore(harnessRoot);

  if (core.issues.length > 0) {
    log.fail(`core/ has ${core.issues.length} problem(s) — nothing was generated:`);
    for (const issue of core.issues) log.detail(`${issue.path} — ${issue.message}`);
    throw new AtrixError('Build aborted.', 'Fix the frontmatter above, then run `atrix build` again.');
  }

  if (!existsSync(p.agentsMd)) throw new AtrixError('AGENTS.md is missing from the harness root.');
  const agentsMd = readFileSync(p.agentsMd, 'utf8');

  const skillCount = buildClaude(harnessRoot, core, agentsMd);
  buildFlatFile(harnessRoot, core, agentsMd, 'codex', 'AGENTS.md');
  buildFlatFile(harnessRoot, core, agentsMd, 'gemini', 'GEMINI.md');
  buildCursor(harnessRoot, core, agentsMd);
  buildOrca(harnessRoot);

  const ruleCount = core.rules.length + core.methodology.length;
  log.ok(
    `built 5 adapters from ${ruleCount} rule(s), ${core.roles.length} role(s), ${skillCount} skill(s)`,
  );
}
