import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { loadCore, type CoreSet, type Doc, type Skill } from '../lib/core.ts';
import { AtrixError, log } from '../lib/log.ts';
import { harnessPaths } from '../lib/paths.ts';

/**
 * Generate per-agent packaging from the portable core.
 *
 * adapters/ is disposable output — never hand-edited. Everything here is derived
 * from core/, which is why adding a new agent is an adapter and not a rewrite.
 */

const GENERATED_BANNER =
  '<!-- GENERATED by `atrix build` from core/. Do not edit — edit core/ and rebuild. -->';

/**
 * Patterns that make generated output machine-specific.
 *
 * adapters/ is committed and consumed on machines that did not produce it, so anything
 * carrying a home directory, a hostname or a username breaks for everyone else. Checked
 * here rather than trusted to memory — see learning/incidents/incident-0003.
 */
const MACHINE_SPECIFIC = [
  { pattern: /\/(Users|home)\/[^/\s"']+/, describes: 'a home directory' },
  { pattern: /\/private\/(tmp|var)\//, describes: 'a machine-local temp path' },
  { pattern: /\/var\/folders\//, describes: 'a macOS per-user temp path' },
];

function write(file: string, contents: string): void {
  for (const { pattern, describes } of MACHINE_SPECIFIC) {
    const found = pattern.exec(contents);
    if (found !== null) {
      throw new AtrixError(
        `Refusing to generate ${file}: it contains ${describes} ("${found[0]}").`,
        'adapters/ is committed and read on other machines. Emit an environment variable such as ${ATRIX_HOME} instead of resolving the path.',
      );
    }
  }

  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, contents.endsWith('\n') ? contents : `${contents}\n`, 'utf8');
}

/**
 * Rules + methodology, concatenated into one document an agent reads on start.
 *
 * `exclude` drops one named layer, which is how the eval suite builds its control arm:
 * the ablation removes exactly the rule under test so a measured difference is
 * attributable to it rather than to the harness in aggregate.
 */
export function renderRuleBundle(core: CoreSet, agentsMd: string, exclude?: string): string {
  const sections = [...core.rules, ...core.methodology]
    .filter((doc) => doc.meta.name !== exclude)
    .sort((a, b) => a.meta.name.localeCompare(b.meta.name))
    .map((doc) => `## ${doc.meta.name}\n\n${doc.body}`);

  return [GENERATED_BANNER, '', agentsMd.trim(), '', '---', '', '# Rules & methodology', '', ...sections].join(
    '\n',
  );
}

function copySkill(harnessRoot: string, skill: Doc<Skill>, destDir: string): void {
  const srcDir = join(harnessRoot, dirname(skill.path));
  mkdirSync(destDir, { recursive: true });
  cpSync(srcDir, destDir, { recursive: true });
}

/**
 * Copy the portable hook scripts and emit the Claude wiring for them.
 * The scripts themselves take a JSON payload on stdin, so other agents that
 * support lifecycle hooks can reuse them without change.
 */
function buildHooks(harnessRoot: string, pluginDir: string): void {
  const src = join(harnessRoot, 'core', 'hooks');
  if (!existsSync(src)) return;

  const destDir = join(pluginDir, 'hooks');
  mkdirSync(destDir, { recursive: true });
  // Tests live beside the hooks they cover; they are not part of the shipped plugin.
  cpSync(src, destDir, { recursive: true, filter: (from) => !from.endsWith('.test.ts') });

  // The plugin root is passed as an argument, not left to the environment: the runtime
  // expands ${CLAUDE_PLUGIN_ROOT} when it builds this command, which is a guarantee.
  const run = (script: string) => `bun run "\${CLAUDE_PLUGIN_ROOT}/hooks/${script}" "\${CLAUDE_PLUGIN_ROOT}"`;

  // The event map lives under a `hooks` key — verified against every installed plugin
  // that ships hooks. Emitting the events at the top level parses fine and silently
  // never fires, which is why adapters.test.ts asserts the shape.
  write(
    join(destDir, 'hooks.json'),
    JSON.stringify(
      {
        description: 'Atrix harness — safety guard, trace recorder, session context.',
        hooks: {
          PreToolUse: [
            { matcher: 'Bash', hooks: [{ type: 'command', command: run('guard-destructive.ts'), timeout: 5 }] },
          ],
          // Records a normalised, redacted shape of each tool result so `atrix observe`
          // can find recurring failures. See the privacy note in the hook itself.
          PostToolUse: [{ hooks: [{ type: 'command', command: run('record-trace.ts'), timeout: 5 }] }],
          SessionStart: [{ hooks: [{ type: 'command', command: run('session-context.ts'), timeout: 5 }] }],
        },
      },
      null,
      2,
    ),
  );
}

/**
 * MCP wiring for the graph server.
 *
 * `${ATRIX_HOME}` rather than a resolved absolute path: adapters/ is committed, so
 * anything machine-specific baked in here breaks CI and every other developer. The
 * server runs from the consuming repo's directory, which is how it finds that repo's
 * .atrix/graph.db; ATRIX_PROJECT_ROOT overrides it when the cwd is not the project.
 */
function mcpConfig(): string {
  return JSON.stringify(
    {
      'atrix-graph': {
        type: 'stdio',
        command: 'bun',
        args: ['run', '${ATRIX_HOME}/packages/graph-mcp/src/server.ts'],
      },
    },
    null,
    2,
  );
}

function buildClaude(harnessRoot: string, core: CoreSet, agentsMd: string): number {
  const out = join(harnessPaths(harnessRoot).adapters, 'claude');
  rmSync(out, { recursive: true, force: true });

  const plugins = [
    {
      name: 'atrix-core',
      description:
        'Atrix harness core — engineering roles, rules, methodology and the learning loop. Install this first.',
    },
    {
      name: 'atrix-skills',
      description: 'The Atrix skill library — engineering, methodology, delivery, infra, documents and communication.',
    },
    { name: 'atrix-stack', description: 'Atrix stack conventions — Next.js, Elysia/Bun, Prisma, Kysely, Expo, Stripe.' },
    {
      name: 'atrix-graphs',
      description:
        'The Atrix code graph over MCP — search, context, callers, callees and blast-radius impact, answered from a local index instead of file reads.',
    },
  ];

  write(
    join(out, '.claude-plugin', 'marketplace.json'),
    JSON.stringify(
      {
        name: 'atrix-harness',
        description: 'The Atrix agent operating system.',
        owner: { name: 'Atrix', email: 'hello@atrix.dev' },
        plugins: plugins.map((p) => ({
          name: p.name,
          description: p.description,
          author: { name: 'Atrix' },
          category: 'productivity',
          source: `./plugins/${p.name}`,
        })),
      },
      null,
      2,
    ),
  );

  for (const p of plugins) {
    const manifest: Record<string, unknown> = {
      name: p.name,
      description: p.description,
      version: '0.1.0',
      author: { name: 'Atrix' },
    };
    // Only atrix-core carries enforcement; the skill plugins are content only.
    if (p.name === 'atrix-core') manifest['hooks'] = ['./hooks/hooks.json'];
    if (p.name === 'atrix-graphs') manifest['mcpServers'] = './.mcp.json';
    write(join(out, 'plugins', p.name, '.claude-plugin', 'plugin.json'), JSON.stringify(manifest, null, 2));
  }

  const coreDir = join(out, 'plugins', 'atrix-core');
  write(join(coreDir, 'AGENTS.md'), renderRuleBundle(core, agentsMd));
  buildHooks(harnessRoot, coreDir);

  const commandsSrc = join(harnessRoot, 'core', 'commands');
  if (existsSync(commandsSrc)) cpSync(commandsSrc, join(coreDir, 'commands'), { recursive: true });

  write(join(out, 'plugins', 'atrix-graphs', '.mcp.json'), mcpConfig());

  for (const role of core.roles) {
    const fm: string[] = [`name: ${role.meta.name}`, `description: ${role.meta.description}`];
    if (role.meta.model !== 'inherit') fm.push(`model: ${role.meta.model}`);
    if (role.meta.tools.length > 0) fm.push(`tools:\n${role.meta.tools.map((t) => `  - ${t}`).join('\n')}`);
    write(join(coreDir, 'agents', `${role.meta.name}.md`), `---\n${fm.join('\n')}\n---\n\n${role.body}`);
  }

  let skillCount = 0;
  for (const skill of core.skills) {
    const plugin = skill.meta.group === 'stack' ? 'atrix-stack' : 'atrix-skills';
    copySkill(harnessRoot, skill, join(out, 'plugins', plugin, 'skills', skill.meta.name));
    skillCount += 1;
  }

  return skillCount;
}

/**
 * The workspace `CLAUDE.md`, which is how the rules reach Claude Code.
 *
 * They cannot ride the SessionStart hook. Claude Code inlines only the first ~2KB of a
 * hook payload once the payload passes ~10,000 characters, silently — so a 38KB bundle
 * delivered the manual head and dropped all 19 rules. `CLAUDE.md` is the native path for
 * always-on content and has no such cap.
 *
 * The bundle is **inlined rather than `@`-imported**: an import path resolves against the
 * agent's working directory, not against the file holding it, so `@adapters/...` worked at
 * the harness root and resolved to nothing from `projects/anything`. Inlining is the only
 * form that survives being read from a subdirectory — which is where all real work happens.
 *
 * See `learning/incidents/incident-0007`.
 */
function buildWorkspaceClaudeMd(harnessRoot: string, core: CoreSet, agentsMd: string): void {
  // renderRuleBundle already stamps a generated-file line; extend that one rather than
  // stacking a second banner on top of it.
  const note = [
    '<!--',
    '  GENERATED by `atrix build` from core/. Do not edit — edit core/ and rebuild.',
    '',
    '  The rules live in this file, rather than in the SessionStart hook, because Claude Code',
    '  inlines only the first ~2KB of a hook payload once it passes ~10,000 characters. They are',
    '  inlined rather than @-imported because an import resolves against the working directory,',
    '  so it evaluates to nothing from projects/*. See learning/incidents/incident-0007.',
    '-->',
  ].join('\n');

  const bundle = renderRuleBundle(core, agentsMd).replace(
    '<!-- GENERATED by `atrix build` from core/. Do not edit — edit core/ and rebuild. -->',
    note,
  );
  write(join(harnessRoot, 'CLAUDE.md'), bundle);
}

/** Codex and Gemini read a single markdown file; the bundle is the whole payload. */
function buildFlatFile(harnessRoot: string, core: CoreSet, agentsMd: string, agent: string, filename: string): void {
  const out = join(harnessPaths(harnessRoot).adapters, agent);
  rmSync(out, { recursive: true, force: true });
  write(join(out, filename), renderRuleBundle(core, agentsMd));

  // Skills are still useful to these agents as reference material they can be pointed at.
  for (const skill of core.skills) copySkill(harnessRoot, skill, join(out, 'skills', skill.meta.name));

  // Codex, Gemini and Cursor all consume MCP; the wiring differs only in where the
  // file lives, so emit it and let ADOPTION.md say where to put it.
  write(join(out, 'mcp.json'), mcpConfig());
}

/** Cursor uses .mdc rule files with per-rule glob scoping. */
function buildCursor(harnessRoot: string, core: CoreSet, agentsMd: string): void {
  const out = join(harnessPaths(harnessRoot).adapters, 'cursor');
  rmSync(out, { recursive: true, force: true });

  write(join(out, '.cursor', 'rules', '000-atrix-entry.mdc'), `---\nalwaysApply: true\n---\n\n${agentsMd.trim()}`);

  for (const doc of [...core.rules, ...core.methodology]) {
    write(
      join(out, '.cursor', 'rules', `${doc.meta.name}.mdc`),
      `---\ndescription: ${doc.meta.description}\nglobs: ${doc.meta.applies.join(',')}\n---\n\n${doc.body}`,
    );
  }
}

/** Orca launches other agents; it needs to know which adapter each one consumes. */
function buildOrca(harnessRoot: string): void {
  const out = join(harnessPaths(harnessRoot).adapters, 'orca');
  rmSync(out, { recursive: true, force: true });
  write(
    join(out, 'atrix-agents.json'),
    JSON.stringify(
      {
        $comment: 'Generated by `atrix build`. Maps each Orca-launchable agent to its generated adapter.',
        agents: {
          claude: { entry: 'adapters/claude/plugins/atrix-core/AGENTS.md', marketplace: 'adapters/claude' },
          codex: { entry: 'adapters/codex/AGENTS.md' },
          gemini: { entry: 'adapters/gemini/GEMINI.md' },
          cursor: { entry: 'adapters/cursor/.cursor/rules' },
        },
      },
      null,
      2,
    ),
  );
}

export function build(harnessRoot: string): void {
  const p = harnessPaths(harnessRoot);
  const core = loadCore(harnessRoot);

  if (core.issues.length > 0) {
    log.fail(`core/ has ${core.issues.length} problem(s) — nothing was generated:`);
    for (const issue of core.issues) log.detail(`${issue.path} — ${issue.message}`);
    throw new AtrixError('Build aborted.', 'Fix the frontmatter above, then run `atrix build` again.');
  }

  if (!existsSync(p.agentsMd)) throw new AtrixError('AGENTS.md is missing from the harness root.');
  const agentsMd = readFileSync(p.agentsMd, 'utf8');

  const skillCount = buildClaude(harnessRoot, core, agentsMd);
  buildWorkspaceClaudeMd(harnessRoot, core, agentsMd);
  buildFlatFile(harnessRoot, core, agentsMd, 'codex', 'AGENTS.md');
  buildFlatFile(harnessRoot, core, agentsMd, 'gemini', 'GEMINI.md');
  buildCursor(harnessRoot, core, agentsMd);
  buildOrca(harnessRoot);

  const ruleCount = core.rules.length + core.methodology.length;
  log.ok(
    `built 5 adapters from ${ruleCount} rule(s), ${core.roles.length} role(s), ${skillCount} skill(s)`,
  );
}
